### ISSUE TITLE
Unable to shoot or reload coral cannon

### ISSUE THREAD

**Issue by FatSassin** [hocha113/CalamityOverhaul#2]
Shooting the coral cannon just makes the sound effect, there's no projectile. Right clicking does nothing.
Mods: Calamity, Infernum, CalamityOverhaul (obviously), Catalyst Mod, Fargo Mutant, Fargo Souls, Fargo Souls DLC, Fargo Souls x Calamity Compability

**Comment by FatSassin** [comment]
Edit. Exiting the game fixed it

**Comment by hocha113** [comment]
Alright, I think I'll fix this. However, currently, I can't reproduce this issue, so it won't be fixed quickly.

**Comment by hocha113** [comment]
You can try the updated version 0.331; it should have addressed this. However, it's just a guess as I couldn't pinpoint the exact conflicting mod. Yes, this issue is not with the mod itself but arises from a conflict with an unknown third-party mod. So, to completely fix it, I need to identify the conflicting object
