### ISSUE TITLE
Murasama doesn't hit when you spam it.

### ISSUE THREAD

**Issue by Shadowblitz16** [hocha113/CalamityOverhaul#23]
If you click repeatedly instead of holding the left mouse button murasama swings really fast but doesn't hit anything.

**Comment by hocha113** [comment]
I think it might be because the code instruction `Owner.itemTime = 2` in the held projectile makes its attack cooldown extremely short (only two frames). However, this functionality is consistent with the original Calamity mod. I believe unmodified items exhibit the same behavior, so I will conduct specific tests to verify this. Whether this is considered an issue is worth discussing. If it does indeed harm the gameplay experience, then I should "fix" it by ensuring it adheres to the attack cooldown set in the weapon's stats, preventing players from rapidly clicking to attack at a high frequency.

**Comment by hocha113** [comment]
From a code perspective, the normal attack of Oni Muramasa consists of three slashes. The original issue was that releasing the left mouse button would immediately terminate the attack, abruptly interrupting the attack animation. In this push, I added a `CanAttemptDead` field, which ensures that the attack can only be terminated after at least one slash is completed. In a sense, this introduces a forced end lag to complete one attack. If necessary, you can pull the code and build the mod yourself to test and see if this change is satisfactory.
https://github.com/hocha113/CalamityOverhaul/commit/4a6d70a2384e9f6c710bfedb6ce1c86758b006f7
